### ISSUE TITLE
Issue with launchd

### ISSUE THREAD

**Issue by tinycg** [maddox/wallop#10]
Several months ago when I first set this up I was able to install the process and have it boot on startup. However in the past month or so (first time getting to reporting it) the process says its already installed but it doesnt appear to boot automatically or recover from being stopped, I have manually launch it.

I've attempted numerous uninstall / reinstalls and just think I'm not doing something in the right order to clean up whatever went wrong.

Any suggestions?

**Comment by maddox** [comment]
Closing this due to age.
