### ISSUE TITLE
Not Showing on CentOS release 6.2 (Final) x64

### ISSUE THREAD

**Issue by lsac** [maddox/wallop#24]
I have compiled ffmpeg by following Centos instruction at https://trac.ffmpeg.org/wiki/CentosCompilationGuide.

I see a dark grey frame saying "Stream is ready", but nothing is playing from channel 600. I am using FIOS in NJ. The top of ffmpeg log is as below. If you knew the fix, this would be a quickie for me. Otherwise, I will have to find time to dig into ffmpeg code to find the fixes.

[mpeg2video @ 0x205ca60] Invalid frame dimensions 0x0.
    Last message repeated 24 times
[mpegts @ 0x2057040] Could not find codec parameters for stream 2 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[ac3 @ 0x205d4c0] frame sync error
Error while decoding stream #0:1: Invalid data found when processing input
[mpegts @ 0x2057040] PES packet size mismatch
    Last message repeated 1 times
[ac3 @ 0x205d4c0] exponent out-of-range
[ac3 @ 0x205d4c0] error decoding the audio block
[mpegts @ 0x2057040] PES packet size mismatch
[ac3 @ 0x205d4c0] frame sync error
Error while decoding stream #0:1: Invalid data found when processing input
[mpeg2video @ 0x205ca60] ac-tex damaged at 7 64
[mpeg2video @ 0x205ca60] 00 motion_type at 41 5
[mpeg2video @ 0x205ca60] invalid mb type in P Frame at 36 6

**Comment by maddox** [comment]
Closing this due to age.
