### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jevinskie** [maddox/wallop#31]
Wallop is really nifty! I'm most excited that it seems to provide a ffmpeg configuration that doesn't freeze during streaming. Thanks!

I was wondering if you had any suggestions for hooking wallop up to some sort of proxy running elsewhere. I have a server that has great upstream bandwidth but my home connection (where my tuner is) does not. It would be nice to support multiple clients watching the same stream while only paying for the bandwidth 1x out of my home connection.

I was thinking about using the nginx-rtmp-module.

**Comment by maddox** [comment]
Closing this due to age.
