### ISSUE TITLE
Apache2 proxy via location

### ISSUE THREAD

**Issue by skug67** [maddox/wallop#34]
Not sure if this is something that needs a tweak to the underlying code or my own stupidity, but I'm trying to use Apache to proxy to wallop so that I can access my HDHR remotely from work and other firewalled locations (where port 8888 is blocked).

My apache config file contains the following:

     <Location /wallop>
     ProxyPass http://[wallop host]:8888/
     ProxyPassReverse http://[wallop host]:8888/
     RequestHeader set X-Forwarded-Proto "https"
     Order Deny,Allow
     Deny from all
     allow from [my specified IPs/domains]
     Satisfy any
     </Location>

When I got to https://[my apache host]/wallop I clearly get directed to the wallop server.  But none of the urls that wallop generates internally to redirect between favorites/all channels/streams are rewritten to have an initial "wallop" so I quickly get bounced away from wallop and back to the main apache server (where it of course dies with a 404 file not found error).  Is there some easy tweak I could do to install a "wallop/" prefix to all of the internally generated urls?

Thanks,

Seth Green

**Comment by guyhalestorm** [comment]
Hey Seth,

I know it's been several months, but it looks like you need to use ModRewrite to fix the URLs.  Maybe something like:

    RewriteEngine On
    RewriteRule wallop/(.*)$ http://localhost:8888/ [P]

Not sure if that's the right format, but I think that'll get you going.

**Comment by skug67** [comment]
Thanks.  I've actually moved on and now use Emby for streaming both live and recorded video.
