### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by ipstatic** [maddox/wallop#40]
I have created a Docker image which contains the latest FFMPEG and Wallop. It can be found here: 

https://registry.hub.docker.com/u/ipstatic/wallop/

I don't know if you would like to add it to the README or some other means to communicate it to anyone interested. Let me know if I can help in any way (adding a pull request with the updated README for example).

**Comment by maddox** [comment]
Awesome! Thanks. Yeah, if you want to just add a section to the README describing it and linking to it, I'll merge it.

**Comment by ipstatic** [comment]
Sorry I didn't know that I could include this issue number in my pull request to automatically associate it with this issue instead of creating a new one. Closing this issue out since #41 will resolve this issue.
