### ISSUE TITLE
Viewing Timeout?

### ISSUE THREAD

**Issue by mhohman** [maddox/wallop#43]
Is is possible to have a viewing timeout? I've noticed over the course of a few weeks we have 1 or 2 sessions that just keep going. I'm not sure if this is due to a roku just getting left playing or if the roku didn't close the session properly.

If it's not something that can easily be implementing I guess we could just restart the wallop server via cron but I'd love a more elegant solution.

Thanks!

**Comment by maddox** [comment]
There is definitely a time out implemented. I think it's about 60 seconds. 

Every time an HLS client makes a request, it resets the session. So if a player stops playing, after 60 seconds the tempeh process should be killed. 

That being said, there's always a possibility that there's a bug, heh.

**Comment by maddox** [comment]
Closing this due to age.
