### ISSUE TITLE
Ceton

### ISSUE THREAD

**Issue by caldwelljt2** [maddox/wallop#48]
Forgive me if this isn't the place or best place to request this, however I've looked endlessly for another solution and this appears to be the only thing close to what I need.

I have a setup that uses a 6 tuner ETH6 from Ceton, which in practice is the same as a HDHomeRun with less software support. The Ceton works well and uses only one cable card,  which for reasons I won't go into was a requirement for me.

I'm interested in either customizing a solution or pulling together a few different pieces to enable my various android, roku, and perhaps RaspberryPI/xbmc devices as extenders to view live and/or recorded content either directly from the ETH6 and/or from the WMC 

Let me know where else I should seek information if this is not the best place.

**Comment by maddox** [comment]
Hiya, Ceton does not provide a good public API to do this. And on top of that they're practically out of business. So more than likely Wallop won't support Ceton devices.

Thanks!
