### ISSUE TITLE
Expose bitrate, encoder, and other params in config

### ISSUE THREAD

**Issue by mjigmond** [maddox/wallop#62]
This is a suggestion for a future enhancement. I am using the graphics accelerated ffmpeg which uses a different video codec, h264_qsv instead of libx264. I'm also using wallop in conjunction with Roku-HDHomeRun and the quality seems to default to 3000k, but I would like it higher (ideal for hardwired connections). I also like to copy the audio as is instead of defaulting to 2 channel AAC. Thanks.

**Comment by maddox** [comment]
Bitrate is [configurable already](https://github.com/maddox/wallop/tree/master/docs#post-channelschanneltune). It's probably being hard coded in Roku-HDHomeRun.

As for the video codec and audio codec stuff, that's fair. I'll look into it.

**Comment by mjigmond** [comment]
It works great, thanks! I'll see if @computmaxer is willing to modify the channel to expose quality settings. Otherwise I'll follow the example in your code changes to expose the bitrate in config.

**Comment by maddox** [comment]
I'll just merge this and you can use the regular checkout.
