### ISSUE TITLE
Preparing/Tuning Stream...

### ISSUE THREAD

**Issue by rajlulla** [maddox/wallop#73]
not sure if anyone is still working on this, but I'm stuck on preparing or tuning stream with this in the logs:
`I, [2017-09-07T21:29:34.997511 #3202]  INFO -- : CHECKING READY STATUS OF SESSION - {:channel=>"804", :pid=>3303, :ready=>false, :last_read=>2017-09-07 21:29:34 -0400}
I, [2017-09-07T21:29:35.497973 #3202]  INFO -- : CHECKING READY STATUS OF SESSION - {:channel=>"804", :pid=>3303, :ready=>false, :last_read=>2017-09-07 21:29:34 -0400}
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0005
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
127.0.0.1 - - [07/Sep/2017:21:29:35 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
I, [2017-09-07T21:29:35.999549 #3202]  INFO -- : CHECKING READY STATUS OF SESSION - {:channel=>"804", :pid=>3303, :ready=>false, :last_read=>2017-09-07 21:29:34 -0400}
I, [2017-09-07T21:29:36.500558 #3202]  INFO -- : CHECKING READY STATUS OF SESSION - {:channel=>"804", :pid=>3303, :ready=>false, :last_read=>2017-09-07 21:29:34 -0400}
127.0.0.1 - - [07/Sep/2017:21:29:36 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0004
127.0.0.1 - - [07/Sep/2017:21:29:36 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0005
127.0.0.1 - - [07/Sep/2017:21:29:36 -0400] "GET /channels/804/status HTTP/1.1" 200 82 0.0003
`

**Comment by jackbiggs** [comment]
Having similar issues... It looks like this repo is orphaned though. A shame since I'd love to be able to watch on my Roku TV.

**Comment by drwahl** [comment]
I know this is a bit of a poor response, but Plex has been working on live TV streaming and has completely replaced my reliance on wallop.  Perhaps others may find Plex's live TV streaming option useful.

**Comment by uofm-matt** [comment]
Unfortunately I second this.  The Plex version of this Just Works (tm).
You have to have the plugin, but otherwise it works great, even with
hardware encoding if you want.  Check it out.

**Comment by jackbiggs** [comment]
I have a Plex server, but I also have a Roku TV, which unfortunately doesn't support Live TV streaming on Plex. :/

**Comment by nodecentral** [comment]
Just adding my support for this issue, I’ve just installed Wallop and any channel I choose gets stuck on the preparing and tuning screens.

Hopefully there’s scope for this to be picked up and addressed - as it looks a cool product and my goal is to embed some iOS/Safari compatible streams of HDHomerun

**Comment by maddox** [comment]
This project is mostly dead. It won’t receive any active development. 

Check out what we made with the knowledge we learned by building Wallop: https://getchannels.com

**Comment by nodecentral** [comment]
Thanks @maddox 

I did wonder :-) 

The challenge I have is that I’ve spent weeks now looking for something that could convert any HDHomerun stream so thar it can be embedded/presented in/via Safari on iOS mobile device.

Wallop looks like it’s tantalisingly close to what to something simple that I’d need. I completely understand this project is mostly dead, but after looking at the other posted is it possible to get some clarity on the set up ?

I’m using the Docker version, but how do I know I have the config set up correctly ? 

> hdhomerun_host = "192.168.102.217"
hdhr_transcode = false
ffmpeg_path = "/diff/ffmpeg/bin/ffmpeg"
transcoding_path = "/diff`"
port = "8888"
hd_start = 1

[ffmpeg]
threads = 4
acodec = "libfaac"
framerate = "29.97"
h264_preset = "superfast"
hls_time = 2
hls_wrap = 40
options = "-loglevel warning -async 1  -tune zerolatency -flags -global_header -fflags +genpts -map 0:0 -map 0:1"

**Comment by maddox** [comment]
I couldn't answer a single question about this project without a lot of research in relearning it, lol. Sorry. It's just been so so long. I didn't even know there was a docker image for Wallop, heh.

Check out Channels though, it does it all for you along with a full guide, DVR,  and remote away from home streaming. Get your time back from all that research and tweaking and just get something that works for ya :) :) :)

**Comment by nodecentral** [comment]
:) :) and I thought my memory was bad :) :)

No problem @maddox - thanks so much for responding.

I’ll look at channels again, but I already have tvheadend for all my DVR and EPG needs,  it was just some transmux’ing (If that’s even a word) that I was after to show content within the iOS / Safari browser - and Wallop looked like a potential perfect fit.

All the best in your new venture(s)

**Comment by srgzx** [comment]
Anyone ever figure this out?  I don't need / want a DVR, or guide, or anything else really -- all I want is transcoding.  SiliconDust pulled their product from the market that has a built in transcoder, too.  Sigh...Any other viable solutions?

**Comment by maddox** [comment]
This project is officially defunct and not being worked on anymore. 

Like mentioned, Channels will absolutely do what you want. Is it free? No. But it would solve your problem. Check out its community forums on all the fun things that people are doing with Channels that aren’t necessarily guide and dvr. 

You can actually get the transcoded streams to use in other things.

https://community.getchannels.com

**Comment by srgzx** [comment]
So after ~ 1 week of tinkering, I finally figured it out.  Sorry, I wasn't going to pay a subscription fee just to get transcoding and web viewing ^_^

I can understand charging for DVR and the guide and all that though, no doubt there's great features there that have value, just not anything I currently need.

If anyone is still interested in this project still...
I'm most likely the only one,but for those who may stumble across this in the future and want it to work:

1.) I'm using the Dockerfile from ipstatic, you need to change the base image to alpine:3.14 -- alpine:latest contains Ruby v3 which breaks some of the gems used by Wallop (I'm not a Ruby dev, but I found other projects on git complaining about the same issue with Thin / Sinatra), 3.14 has Ruby 2.7.6 which works fine.  You also need to add the line "&& gem install bundler:1.11.2 \" 

2.) Make sure ffmpeg location is configured properly in the TOML config, if you're using that Dockerfile it's not going to be in usr/bin or /usr/bin/local, it's going to be /ffmpeg/bin/ffmpeg -- you can always check the ffmpeg.log in /wallop/log to see ffmpeg related errors.

3.) In wallop.rb there's a parameter sent to ffmpeg called "hls_wrap" -- but this appears to be a deprecated flag (I'm not an ffmpeg expert, just googled the error from ffmpeg log), I found a blog post recommending that it be changed to "hls_list_size" -- so I did that, and it seems to work.  

No more errors in ffmpeg.log and the video actually plays.   I believe this is most likely the reason for the "Preparing" stick.  

**So for all of you that actually have this working up until this point (webserver actually loads the page and doesn’t internal server error on you), you probably only need to change this part!

It may be a better idea to leave the code alone and instead edit the dockerfile to grab an older version of ffmpeg.  In fact that’s what I recommend doing, and how I ultimately decided to fix the issue.**

Looks like ffmpeg version 5.0 is where they removed “hls_wrap” - so any version before that should be okay.  I decided on 4.1.

I have produced a modified Dockerfile that fixes all of these issues and builds perfectly.

I'm running my modified Dockerfile image on my M1 mac Mini, and I tested using Chrome and Safari on the same mac.

As I said I'm definitely no dev but after a week of digging into this and researching all the errors, I'm pretty clear about how it works, if anyone is actually stuck let me know I'll see if I can help.

**Comment by srgzx** [comment]
So…I was contemplating forking this, and perhaps updating it for Ruby 3 / ffmpeg 5 and making it better…and I was talking to a friend about it and he directed me to another project called Restreamer.

https://datarhei.github.io/restreamer/

Restreamer works with the HDHomeRun, it runs in a Docker container, and it even does multi-casting, so if you want, you can have multiple people watching a transcoded stream from one tuner…it uses HLS and works on every device / browser I’ve tested it with.  It also has user / pass login.   

It does a lot of other neat stuff too (they just added support for deinterlacing)… it’s in active development, and it’s 100% free and open source.  

I only wish I would’ve found it weeks ago, though I did have fun learning how Wallop works, and teaching myself Docker.
